E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0] failed while attempting to run meta for aten.avg_pool2d.default
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0] Traceback (most recent call last):
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0]     r = func(*args, **kwargs)
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0]     return self._op(*args, **kwargs)
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 2620, in meta_avg_pool2d
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0]     nInputPlane = input.size(-3)
E0127 12:54:42.336000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [352/0] IndexError: Dimension out of range (expected to be in range of [-2, 1], but got -3)
