E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0] failed while attempting to run meta for aten.view.default
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0] Traceback (most recent call last):
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     r = func(*args, **kwargs)
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     return self._op(*args, **kwargs)
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 4664, in view
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     return _reshape_view_helper(a, *shape, allow_copy=False)
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 3702, in _reshape_view_helper
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     shape = utils.infer_size(shape, a.numel())
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/__init__.py", line 939, in infer_size
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     torch._check(
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     ~~~~~~~~~~~~^
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]         numel == newsize,
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]         ^^^^^^^^^^^^^^^^^
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]         lambda: f"shape '{list(shape)}' is invalid for input of size {numel}",
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     )
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     ^
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     _check_with(RuntimeError, cond, message)
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0]     raise error_type(message_evaluated)
E0205 11:32:08.300000 3201829 site-packages/torch/_subclasses/fake_tensor.py:2380] [289/0] RuntimeError: shape '[1, 8, 2, 2, 2]' is invalid for input of size 8
