E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0] failed while attempting to run meta for aten.fractional_max_pool2d.default
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0] Traceback (most recent call last):
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     r = func(*args, **kwargs)
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     return self._op(*args, **kwargs)
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 4666, in meta_fractional_max_pool2d
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     torch._check(
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     ~~~~~~~~~~~~^
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]         self.ndim in (3, 4),
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]         ^^^^^^^^^^^^^^^^^^^^
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]         lambda: f"fractional_max_pool2d: Expected 3D or 4D tensor, but got: {self.ndim}",
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     )
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     ^
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     _check_with(RuntimeError, cond, message)
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0]     raise error_type(message_evaluated)
E0127 12:02:22.784000 1492919 site-packages/torch/_subclasses/fake_tensor.py:2380] [80/0] RuntimeError: fractional_max_pool2d: Expected 3D or 4D tensor, but got: 5
