E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0] failed while attempting to run meta for aten._adaptive_avg_pool3d.default
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0] Traceback (most recent call last):
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     r = func(*args, **kwargs)
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     return self._op(*args, **kwargs)
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 2966, in meta_adaptive_avg_pool3d
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     torch._check(
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     ~~~~~~~~~~~~^
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]         self.ndim == 4 or self.ndim == 5,
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]         lambda: f"Expected 4D or 5D tensor, but got {self.shape}",
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     )
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     ^
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     _check_with(RuntimeError, cond, message)
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0]     raise error_type(message_evaluated)
E0127 13:09:33.440000 3748873 site-packages/torch/_subclasses/fake_tensor.py:2380] [161/0] RuntimeError: Expected 4D or 5D tensor, but got torch.Size([1, 1, 1, 1, s0, s1])
