E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0] failed while attempting to run meta for aten.gather.default
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0] Traceback (most recent call last):
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     r = func(*args, **kwargs)
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     return self._op(*args, **kwargs)
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 5226, in meta_gather
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     gather_shape_check(self, wrapped_dim, index)
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 5208, in gather_shape_check
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     torch._check(
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     ~~~~~~~~~~~~^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]         ensure_nonempty_size(index, i) <= ensure_nonempty_size(self, i),
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]         lambda: f"Size does not match at dimension {i} expected index {index.shape}"
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]         + f" to be no larger than self {self.shape} apart from dimension {dim}",
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     )
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     ^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     _check_with(RuntimeError, cond, message)
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0]     raise error_type(message_evaluated)
E0127 11:37:47.004000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [519/0] RuntimeError: Size does not match at dimension 2 expected index torch.Size([1, 1, ((s0*((s1//4)))//2), ((s0*((s1//4)))//2)]) to be no larger than self torch.Size([1, s0*((s1//4)), 1, 1]) apart from dimension 1
