E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0] failed while attempting to run meta for aten.adaptive_max_pool3d.default
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0] Traceback (most recent call last):
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     r = func(*args, **kwargs)
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     return self._op(*args, **kwargs)
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_decomp/__init__.py", line 123, in _fn
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     return f(*args, **kwargs, out=None if is_none else out_kwargs)
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     result = fn(*args, **kwargs)
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 3087, in meta_adaptive_max_pool3d
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     torch._check(
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     ~~~~~~~~~~~~^
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]         ndim in (4, 5),
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]         ^^^^^^^^^^^^^^^
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]         lambda: f"adaptive_max_pool3d(): Expected 4D or 5D tensor, but got: {input.shape}",
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     )
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     ^
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     _check_with(RuntimeError, cond, message)
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0]     raise error_type(message_evaluated)
E0127 11:40:11.281000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [717/0] RuntimeError: adaptive_max_pool3d(): Expected 4D or 5D tensor, but got: torch.Size([1, s0, 1, 3, 3, s1 + 6])
