E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0] failed while attempting to run meta for aten.mm.default
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0] Traceback (most recent call last):
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     r = func(*args, **kwargs)
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     return self._op(*args, **kwargs)
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     result = fn(*args, **kwargs)
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 2129, in meta_mm
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     torch._check(
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     ~~~~~~~~~~~~^
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]         M1 == M2,
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]         ^^^^^^^^^
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]         lambda: f"a and b must have same reduction dim, but got [{N}, {M1}] X [{M2}, {P}].",
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     )
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     ^
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     _check_with(RuntimeError, cond, message)
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0]     raise error_type(message_evaluated)
E0204 16:24:59.904000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [417/0] RuntimeError: a and b must have same reduction dim, but got [1, 20*(s0 - 2)*(s1 - 2)*(s2 - 2)] X [20, 10].
