E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0] failed while attempting to run meta for aten.expand.default
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0] Traceback (most recent call last):
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     r = func(*args, **kwargs)
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     return self._op(*args, **kwargs)
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 3015, in expand
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     torch._check(
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     ~~~~~~~~~~~~^
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]         guard_size_oblivious(requested_length == x)
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     ...<2 lines>...
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]         lambda: f"expand: attempting to expand a dimension of length {x}!",
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     )
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     ^
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     _check_with(RuntimeError, cond, message)
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0]     raise error_type(message_evaluated)
E0205 14:27:19.068000 1612526 site-packages/torch/_subclasses/fake_tensor.py:2380] [45/0] RuntimeError: expand: attempting to expand a dimension of length 3!
