E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0] failed while attempting to run meta for aten.gather.default
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0] Traceback (most recent call last):
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     r = func(*args, **kwargs)
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     return self._op(*args, **kwargs)
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 5222, in meta_gather
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     torch._check(
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     ~~~~~~~~~~~~^
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]         index.dtype == torch.long,
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]         lambda: f"gather(): Expected dtype int64 for index, but got {index.dtype}",
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     )
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     ^
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     _check_with(RuntimeError, cond, message)
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0]     raise error_type(message_evaluated)
E0124 17:42:35.557000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [441/0] RuntimeError: gather(): Expected dtype int64 for index, but got torch.float32
