E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0] failed while attempting to run meta for aten.avg_pool3d.default
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0] Traceback (most recent call last):
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     r = func(*args, **kwargs)
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     return self._op(*args, **kwargs)
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     result = fn(*args, **kwargs)
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 2815, in meta_avg_pool3d
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     torch._check(
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     ~~~~~~~~~~~~^
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]         input.ndim in (4, 5),
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]         ^^^^^^^^^^^^^^^^^^^^^
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]         lambda: "non-empty 4D or 5D (batch mode) tensor expected for input",
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     )
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     ^
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     _check_with(RuntimeError, cond, message)
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0]     raise error_type(message_evaluated)
E0124 17:39:49.628000 1685906 site-packages/torch/_subclasses/fake_tensor.py:2380] [208/0] RuntimeError: non-empty 4D or 5D (batch mode) tensor expected for input
