E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0] failed while attempting to run meta for aten.view.default
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0] Traceback (most recent call last):
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]     r = func(*args, **kwargs)
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]     return self._op(*args, **kwargs)
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 4664, in view
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]     return _reshape_view_helper(a, *shape, allow_copy=False)
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 3797, in _reshape_view_helper
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0]     raise ValueError(msg)
E0127 12:32:22.884000 2031468 site-packages/torch/_subclasses/fake_tensor.py:2380] [171/0] ValueError: Cannot view a tensor with shape torch.Size([1, 64, 196]) and strides (64, 1, 64) as a tensor with shape (1, 12544)!
